### ISSUE TITLE
pip install -e SCARlink not working

### ISSUE THREAD

**Issue by Dalhte** [snehamitra/SCARlink#16]
Hello there
I'm try to install SCARlink but when I run : 
pip install -e SCARlink
I get : 
      distutils.errors.LinkError: command '/home/david/anaconda3/envs/scarlink-env/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

I try to update/upgrade everything I could but nothing work. Do you have an idea why ?
Best
David

**Comment by snehamitra** [comment]
Could you share list of packages installed in your environment?

**Comment by Dalhte** [comment]
Hello
It's indeed a python incompatibility problem. I'm trying with a virtual env and I will see if it's working
Best
David

**Comment by Dalhte** [comment]
Hi there
I reinstalled everything in a clean new virtual env and preprocessing seems to work on the tutorial data

When running scarlink, I got the output but I have this kind of messages popping : 
>scarlink -o multiome_outTest -g hg38 -c celltype

2024-08-29 09:39:07.382326: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-29 09:39:07.522831: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
I get those everytime I use python3.8 (and never with other python version)

I tried to reinstall Tensorflow and rebuild it but to no end so I'm just ignoring the message.

**Comment by Dalhte** [comment]
It's working on the tutorial data :)
Thanks a lot for this very nice analysis package !
Best
D
