### ISSUE TITLE
Problem with scarlink_plot

### ISSUE THREAD

**Issue by Dalhte** [snehamitra/SCARlink#17]
Hello again
Sorry to bother you but I tried to run Scarlink with my own data this time (work perfectly with yours). I'm working on Rat samples, so I runned the preprocessing with a Rat GTF file (the same I used to analyse my single cell data)
Everything went well until :
scarlink_plot -o multiome_outPG -c cell_Type --genes Abr
Gave me  : 
Traceback (most recent call last):
  File "/home/david/anaconda3/envs/scarlink-env/bin/scarlink_plot", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_plot')())
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/run_scarlink_visualization.py", line 21, in main
    scv.plot_scarlink_output(scarlink_out, genes=genes,
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/src/visualization.py", line 37, in plot_scarlink_output
    rm.plot_gene(gene, groups=celltype, plot_frags=plot_frags, to_save=to_save, plot_dir=scarlink_out['plot_dir'], cmap=cmap, save_format=save_format, figsize=figsize, sort_gex=sort_gex, show_yticks=show_yticks, plot_shap=plot_shap, shap_cmap=shap_cmap, cluster_order=cluster_order, bg_transparent=bg_transparent)
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/src/model.py", line 907, in plot_gene
    plotRegion(chrm, start, end, axn, self.gtf_file)
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/src/plotExtra.py", line 31, in plotRegion
    a = pandas.read_csv(gtf_file, sep = "\t", header = None)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/python38/Python-3.8.16/SCARlink/scarlink/data/genes.gtf'
Closing remaining open files:multiome_outPG/coassay_matrix.h5...done

So I put the GTF were it was searched for and I get : 
Traceback (most recent call last):
  File "/home/david/anaconda3/envs/scarlink-env/bin/scarlink_plot", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_plot')())
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/run_scarlink_visualization.py", line 21, in main
    scv.plot_scarlink_output(scarlink_out, genes=genes,
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/src/visualization.py", line 37, in plot_scarlink_output
    rm.plot_gene(gene, groups=celltype, plot_frags=plot_frags, to_save=to_save, plot_dir=scarlink_out['plot_dir'], cmap=cmap, save_format=save_format, figsize=figsize, sort_gex=sort_gex, show_yticks=show_yticks, plot_shap=plot_shap, shap_cmap=shap_cmap, cluster_order=cluster_order, bg_transparent=bg_transparent)
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/src/model.py", line 907, in plot_gene
    plotRegion(chrm, start, end, axn, self.gtf_file)
  File "/home/david/python38/Python-3.8.16/SCARlink/scarlink/src/plotExtra.py", line 31, in plotRegion
    a = pandas.read_csv(gtf_file, sep = "\t", header = None)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 812, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 873, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 848, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2025, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 9

Do you have already encounter this kind of problems ?
Best
David

**Comment by snehamitra** [comment]
Could you share the GTF file that you used? I can take a look and try reproducing the error.

**Comment by Dalhte** [comment]
Hello !
You were right, my GTF (custom made)  have some perculiarity that are not well accepted by SCARlink, I rerunned using the refseq official one, and the plot is drawn now.
However, the plot is incomplete: for exemple : 
![Fshb](https://github.com/user-attachments/assets/e65c92dd-3960-4001-937c-08cf223569c4)

As you see, there is no clusters ! 

I opened the gene_linked_tiles_cell_Type.csv.gz file and the cell_Type column is full of numbers (1 2 3...) and not with the name of my cell clusters. 
To transfert celltype id from seurat to arch object, I did : 
projPG <- addGeneIntegrationMatrix(
  ArchRProj = projPG, 
  useMatrix = "GeneScoreMatrix",
  matrixName = "GeneIntegrationMatrix",
  reducedDims = "IterativeLSI",
  seRNA = integrated,
  addToArrow = FALSE,
  groupRNA = "celltype",
  nameCell = "predictedCell_Un",
  nameGroup = "predictedGroup_Un",
  nameScore = "predictedScore_Un"
)
Where "integrated" is my seurat scRNAseq object.
Then I run a renamecells to harmonize between "_" and "#" and things are looking okay.

I figured that maybe calling the cell type "predictedGroup_Un" wasn't the smartest move so I reruned it modifying "predictedGroup_Un" with "celltype". I will know if that works tomorrow in the morning, but if  you have a better way to harmonize seurat and archR object from the same 10X experiments, I will gladly change things accordingly

Thanks a lot for you help, I really appreciate it.

Best

D

**Comment by Dalhte** [comment]
Hello again
So I tried to run with the correction "predictedGroup_Un" to "celltype" to have a celltype column in the ArchR object, but it didn't changed anything (plot looks the same)
I also tried without transferring the cell cluster ID (celltype only in the Seurat and not in the ArchR) and I got the same thing again :   the cell_Type column of the gene_linked_tiles_cell_Type.csv.gz file  is full of numbers (1 2 3...) and there is no cluster on the plot.
It would help me if you can give me the code you used to transfer the cluster ID from seurat to archR for the PBMC tuto. The architecture of your PBMC archR object looks very different from mine : 
 you have : 
projPBMC@projectMetadata@listData$GroupCoverages@listData$Params@listData$cellGroups$
while I got : 
projPG@cellColData@listData$celltype$
And I don't know how to get the same architecture than you
Best
David

**Comment by snehamitra** [comment]
Hi David, the Seurat and ArchR objects are only used for the preprocessing step `scarlink_processing`. Then all the subsequent steps use the processed files `coassay_matrix.h5` and `cell_info.txt`. Could you check if the correct cell type annotation column is present in `cell_info.txt`? Otherwise, you can add the column using `scarlink_add_cell_cluster`.

Links with details about adding new columns to `scarlink` objects:
https://github.com/snehamitra/SCARlink/blob/main/notebooks/tutorial.ipynb
https://github.com/snehamitra/SCARlink/wiki/8.-Adding-new-cell-grouping

Once you have added the column, you can re-run `scarlink` and `scarlink_tiles`. Running `scarlink` again with the updated annotations will not take too long this time since you already have the trained models.

**Comment by Dalhte** [comment]
Hello
Thanks for the rapid answer :)
There is a celltype column filled with the appropriate cell type names in the cell_info.txt
Here is a simplified version (with only the 4 first cells). You will see that I have two column, one named cell_Type (my orignial column) and one named celltype (I remained the clusters fearing that the problem was with the underscore in the names) . Runing Scarlink function with either -c cell_Type or -c celltype has the same results.
[cell_info.txt](https://github.com/user-attachments/files/16896891/cell_info.txt)

Is there a way to check if the celltype info are stored correctly in the coassay_matrix.h5 ?

**Comment by Dalhte** [comment]
Hello again
I asked ChatGPT to help me to understand the coassay_matrix.h5 files
For the tutorial dat
When I do
>>> with h5py.File('pbmc_test_input/multiome_out/coassay_matrix.h5', 'r') as f:
...     dataset = f['cell_info']
...     data = dataset[:]
...     print(data)
... 

I get : 
[(1, 8379., 3307, b'**CD4 Naive**', b'pbmc', 15.853, 24569., 23619., 461., 0.33238109, 1., 1.34196823, 6824., 15171., 35530., 13535., -0., 0.45454545, 0.00648748, b'C15', b'3', 7486., 3107., 0.00280524, 0.16096714, 40989., 0.57683864, b'pbmc#AAACAGCCAAGGAATC-1')

With my data : 

>>> with h5py.File('multiome_outPS/coassay_matrix.h5', 'r') as f:
...     dataset = f['cell_info']
...     data = dataset[:]
...     print(data)


[(b'PS', 2352., 1474, 4085., 3880, 1935., 1277, 0.57601626, 0.68, 5.52780553, 0.86, b'AAACAGCCAATTAGCT-1', b'ACAGCGGGTCCAAATC-1', 1, 0, 6510, 6092, 551, 1874, 3365, 1573, 299, 548, 1021, 2063, 1290,  725, 1331, 1517, 2352,  7164,  63, 280,  867,  8, 0,  5946, 2021, 3875, 7310, nan, 0., 4091., 3860, 2343., 1473, 0.50623493, 0.49376507,  2, 2, b'PG24', 2, 15.261, 578., 2536., 2., 0.21325261, 1., 0.81612706,  798., 3274.,  5946., 1874., 1.68180289e-04, b'PS#AAACAGCCAATTAGCT-1')
The cell type are not passed to the coassay matrix...
Any idea why ? My seurat object is quite complicated (I run seurat, soupX signac, chromVar.... Should I try with a more simple object with less column in the metadat ?

**Comment by snehamitra** [comment]
Was the column not added even after using `scarlink_add_cell_cluster`?

Code snippet to extract `celltype` column in `coassay_matrix.h5`:

```python
import pandas
f = pandas.HDFStore("coassay_matrix.h5", "r")
df = f.select('cell_info')
print(f['celltype'])
print(f['celltype'].unique()) # also check the unique values in the column
f.close()
```

**Comment by Dalhte** [comment]
I'm so sorry but it's a nightmare.
I did the scarlink_add_cell_cluster ranaming celltye as celltype1
In the cell_info.txt, the celltype1 column is added, in the coassay_matrix : 
import pandas
f = pandas.HDFStore("coassay_matrix.h5", "r")
df = f.select('cell_info')
print(f['celltype1'])
print(f['celltype1'].unique()) # also check the unique values in the column
f.close()

give : 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/pytables.py", line 596, in __getitem__
    return self.get(key)
  File "/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/pandas/io/pytables.py", line 790, in get
    raise KeyError(f"No object named {key} in the file")
KeyError: 'No object named celltype1 in the file'

I have an other error message above, concerning unrelated info present in my seurat object such as orig.ident : 
>/home/david/anaconda3/envs/scarlink-env/lib/python3.8/site-packages/tables/path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'orig.ident'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

I have the same message for every column head containing a dot ('TSS.enrichment', 'percent.mtPG24'....)
Could this problem prevent adding the cell type info ? should I rerun my seurat avoiding all the dot containing heads ?

**Comment by snehamitra** [comment]
You could try re-running with a new Seurat object but I'm not sure if the dots in the column names are causing the issue. Could you share a snapshot of the `.txt` file you're using to add the `celltype1` column to the object using `scarlink_add_cell_cluster`?

**Comment by Dalhte** [comment]
Hello again
I tried to run with both my integrated seurat object and just on of the samples, I got the same problem each time
Here is the .txt
[celltype1.txt](https://github.com/user-attachments/files/16959070/celltype1.txt)
For me it looks very similar to the cell_info_new_ann.txt for PBMC
Best
D

**Comment by Dalhte** [comment]
oh sorry I forgot to join the coassay_matrix file
Here it is my out put dossier with all the file (cell_info, coassay.....)
As it is too big, i used renater transfett file, the offical system of French academia (it is secured and risk free)
https://filesender.renater.fr/?s=download&token=e76a3d03-a9f3-4309-81ef-e6a4ecc3e79a
It is the files before the scarlink_add_cell_cluster
Here is the celltype1.txt : 
[celltype1.txt](https://github.com/user-attachments/files/16965347/celltype1.txt)

I'm going to try manual adding but if you can have an eye on the coassay_matrix, I fear that my problem could ran deeper than expected

Thanks a lot for your time !

**Comment by snehamitra** [comment]
Adding comments about two of your reported issues:

#### Issue 1: unable to add new annotation column

The number of cells in your scarlink object (9172 cells) is different from the number of cells in `celltype1.txt` (9894 cells). So, in order to add cell types for the matched cells, you need to provide the cell name column `--cellcol`. In your case, it is `cell_name` in `celltype1.txt`. I added `celltype1` to the scarlink object using the following command:

```bash
scarlink_add_cell_cluster -o multiome_outPS -f multiome_outPS/celltype1.txt --colname celltype1 --cellcol cell_name
```

Checking if `celltype1` is present in `coassay_matrix.h5`:

```python
>>> import pandas
>>> f = pandas.HDFStore("multiome_outPS/coassay_matrix.h5", "r")
>>> df = f.select('cell_info')
>>> print(df['celltype1'])
0              Lactotrope
1       Folliculostellate
2              Lactotrope
3             Somatotrope
4              Lactotrope
              ...        
9166    Folliculostellate
9167          Somatotrope
9168           Thyrotrope
9169          Somatotrope
9170          Gonadotrope
Name: celltype1, Length: 9171, dtype: object
>>> print(df['celltype1'].unique())
['Lactotrope' 'Folliculostellate' 'Somatotrope' 'Corticotrope'
 'Marcrophage' 'Pericyte' 'Endothelial' nan 'Gonadotrope' 'Thyrotrope'
 'Melanotrope']
>>> f.close()
```

Note that your file `celltype1.txt` file does not include annotations for all cells in the scarlink object. These would be labeled as `nan` and excluded from the plots. 

#### Issue 2: missing data in output plots (Fixed code)

There were additional columns in your scarlink object that have `nan` values. Before plotting, I filter out `nan` values `self.cell_info.dropna()[groups]` and that was resulting in the empty plots. I updated the `nan` filtering to `self.cell_info[groups].dropna()`. I can now generate the plots from your data. Adding the plot for Nr4a1 from your analysis.

_**Please download the latest repository to access the fixed version of the plotting code.**_

![Nr4a1](https://github.com/user-attachments/assets/c0f424c5-ad0a-4454-9936-e546af46a885)

**Comment by Dalhte** [comment]
Hello
Thanks a lot ! It's working :) So glad about it.
I added the 'rn7' entry in my local run_scarlink.py : 

    parser.add_argument('-g', '--genome', required=True, type=str, help="Default genome choices include mm10, hg38, hg19, rn7. Alternatively, a GTF file can be provided as input.") # , choices=['mm10', 'hg38', 'hg19', 'rn7']
...
... and
    if gtf_file in ['mm10', 'hg19', 'hg38', 'rn7']:
        gtf_file = path + '/data/' + gtf_file + '.refGene.gtf.gz'
Thanks again for your precious help !

Best

David

**Comment by Dalhte** [comment]
I may have an additional question (sorry)
Is it possible to restrict the rest of the analysis (the chromatin potential) to only chosen cell type without subsetting the seutat.object first and rerunning the scarlink pipeline ?

**Comment by snehamitra** [comment]
It is not implemented. But one workaround would be to modify the [`plot_arrows()`](https://github.com/snehamitra/SCARlink/blob/main/scarlink/src/chromatin_potential.py#L426) function to restrict the arrow visualization to a subset of cell types. For example if `cell_idx = [0, 1, 5, 10, ...]` corresponds to the indices of your cell types of interest, you can modify the [last line](https://github.com/snehamitra/SCARlink/blob/main/scarlink/src/chromatin_potential.py#L477C5-L479C56) of the `plot_arrows` function as:

```python
plt.quiver(x_smooth[cell_idx], y_smooth[cell_idx],
               (u_smooth/E_norm_smooth)[cell_idx], (v_smooth/E_norm_smooth)[cell_idx], 
               angles='xy', scale_units='xy', **kwargs)
```

**Comment by Dalhte** [comment]
Thanks a lot for your help
I have a last question : is it possible to change the size of the genomic window in the plots ?
Best
David

**Comment by snehamitra** [comment]
You can modify the default window size of [plotting](https://github.com/snehamitra/SCARlink/blob/main/notebooks/output_visualization.ipynb) as follows:

```python
scv.plot_scarlink_output(scarlink_out, genes=['ZEB2'], celltype='celltype', figsize=(8,10), to_save=False)
ax = plt.gca()
ax_list = plt.gcf().axes

atac_ax_list = [ax_list[0]] + list(filter(lambda x: x.get_ylabel() != '', ax_list))
for atx in atac_ax_list:
    print(atx.get_xlim()) # get the genomic window; Example output: (1909500.0, 2411500.0)
    atx.set_xlim(1909500 + 80000, 2411500 - 80000) # shrink the genomic window by 80kb from both sides 

plt.show() 
```

**Comment by Dalhte** [comment]
Thanks a lot ! 
You have been so helpfull. I really appreciate
Best
David
