### ISSUE TITLE
Trouble with using the package

### ISSUE THREAD

**Issue by yiman589** [snehamitra/SCARlink#2]
Hi,

I have been able to download and install the package, and I can call the function scarlink_processing with no trouble. However, when I tried to run the rest of the functions scarlink, scarlink_tiles and scarlink_plot, I got error messages of **Illegal instruction: 4**. I am on a Mac with M1 chip. Could you provide any insights or solutions to this? Any help is appreciated!

Thanks a lot!

**Comment by snehamitra** [comment]
Could you check if the issue is related to importing tensorflow? 
https://github.com/tensorflow/tensorflow/issues/25822

**Comment by yiman589** [comment]
Thanks for your reply!

Yes, it is related to importing tensorflow, but I haven't found a solution yet. I will keep looking into it. Thank you for your help!
