### ISSUE TITLE
Error in seq() during data preprocessing: "invalid '(to - from)/by'"

### ISSUE THREAD

**Issue by sainathmamde** [snehamitra/SCARlink#20]
First of all, thank you for developing this great tool! I encountered an error while preprocessing the data using the following section of code:
if (ncores > 1) {
    bpparam <- MulticoreParam(workers = ncores)
} else {
    bpparam <- BiocParallel::SerialParam()
}

# Create chunks
max_ix <- min(length(selected.genes), max(trunc(length(selected.genes) / 50), 50))

tmp_files <- bplapply(1:max_ix, FUN = function(i) {
    selected.genes.subset <- selected.genes[seq(i, length(selected.genes), max_ix)]
    split_write_hdf5(out_dir, selected.genes.subset, tm.filtered[rowData(tm.filtered)$symbol %in% selected.genes.subset, ])
}, BPPARAM = bpparam)

The error I receive. 
[1] "Tile size: 500"
character(0)
[1] 0
R[write to console]: Error: BiocParallel errors
  1 remote errors, element index: 1
  1 unevaluated and other errors
  first remote error:
Error in seq.default(i, length(selected.genes), max_ix): invalid '(to - from)/by'

R[write to console]: In addition: 
R[write to console]: There were 14 warnings (use warnings() to see them)
R[write to console]: 

Traceback (most recent call last):
  File "/tscc/nfs/home/smamde/miniconda3/envs/scarlink-env/bin/scarlink_processing", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_processing')())
  File "/tscc/nfs/home/smamde/SCARlink/scarlink/preprocessing/create_h5_files.py", line 44, in main
    rfunc.write_files(archr_out, seurat_out, out_dir, args.window, args.ncores, args.scale)
  File "/tscc/nfs/home/smamde/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 208, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/tscc/nfs/home/smamde/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/tscc/nfs/home/smamde/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/tscc/nfs/home/smamde/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: BiocParallel errors
  1 remote errors, element index: 1
  1 unevaluated and other errors
  first remote error:
Error in seq.default(i, length(selected.genes), max_ix): invalid '(to - from)/by'

**Comment by snehamitra** [comment]
Can you check how many variable genes you have in your Seurat object? Do you get the same error if you run `scarlink_processing` with `-nc 1`?

**Comment by sainathmamde** [comment]
Thank you for your prompt response, @snehamitra! I didn’t have any highly variable genes, but I was able to resolve the error. I have one more question: How long should it typically take to process 70K cells using 128 cores? My job has been running for over 27 hours.

**Comment by snehamitra** [comment]
Is it running on a compute cluster split over 128 jobs? You can check if it has generated 128 log files. Also, it runs faster on cpu.

**Comment by sainathmamde** [comment]
Yes I'm using CPU. It has generated only 1 log file. 

This is the command I used 
scarlink_processing  --scrna obj_liver_hepatocyte_subset_RNA_update_meta_data_senescent_like_addMeta_scarlink.RDS --scatac /archr_scarlink_heapotocytes/  -o /scarlink/sdtmc_subset -nc 128 --window 300000

**Comment by snehamitra** [comment]
I misunderstood before. I thought it was taking 27 hours for `scarlink` and not `scarlink_processing`. `scarlink_processing` should not take that long and will only generate one log file. Can you check if the file `coassay_matrix.h5` is created?

**Comment by sainathmamde** [comment]
My mistake, I meant scarlink itself. This is my code, and it's not parallelizing. I've tried multiple methods, but nothing seems to work.
#!/bin/bash
#SBATCH -J OCT232024scarlink_hepatocytes #Optional, short for --job-name
#SBATCH -N 1 #Number of nodes
#SBATCH -n 32  #Total number of tasks increase this number to increase parallelization
#SBATCH -c 1 #Number of threads per process
#SBATCH -t 35:00:00 #Short for --time walltime limit
#SBATCH -o /tscc/nfs/home/smamde/cluster-logs/%x.%j.%N.out #standard output name
#SBATCH -e /tscc/nfs/home/smamde/cluster-logs/%x.%j.%N.err #Optional, standard error name
#SBATCH -p condo #Partition name
#SBATCH -q condo #QOS name
#SBATCH -A csd788 #Allocation name
#SBATCH --mem 500G #Memory
#SBATCH --mail-type END #Optional, Send mail when job ends



scarlink_processing  --scrna liver_sennet_atac/obj_liver_hepatocyte_subset_RNA_update_meta_data_senescent_like_addMeta_scarlink.RDS --scatac liver_sennet_atac/archr_scarlink_heapotocytes/  -o liver_sennet_atac/scarlink/ 

scarlink -o liver_sennet_atac/scarlink/ -g mm10 -np 32 -c new_clusters  --sparsity 0.90

**Comment by snehamitra** [comment]
First run `scarlink_processing` as a separate job. Then you can submit the `scarlink` run as a job array:

```bash
#SBATCH --ntasks=1 --array=1-101 # number of parallel jobs in the job array
...
# running scarlink
scarlink ... -p $SLURM_ARRAY_TASK_ID -np 100 # [-np should be set to the same value as the size of the job array]
```

**Comment by sainathmamde** [comment]
I really appreciate taking time to walk me through this. It worked. 
Thank you so much. 
Sainath

**Comment by zhangchuyi** [comment]
@snehamitra @sainathmamde I met a same problem. Could you please tell me how did you solve it? 
This is the code I used:
`scarlink_processing --scrna rna_seurat.filtered.rds  --scatac ArchR_ATAC_project -o multiome_out -nc 1 --window 300000`

And these are the error screen output:
"
...
R[write to console]: 2025-04-30 14:58:29 : Constructing SummarizedExperiment, 1.355 mins elapsed.
R[write to console]: 2025-04-30 14:58:30 : Finished Matrix Creation, 1.366 mins elapsed.

[1] "Tile size: 500"
R[write to console]: Error: BiocParallel errors
  1 remote errors, element index: 1
  1 unevaluated and other errors
  first remote error:
Error in seq.default(i, length(selected.genes), max_ix): invalid '(to - from)/by'

R[write to console]: In addition:
R[write to console]: There were 15 warnings (use warnings() to see them)
R[write to console]:

Traceback (most recent call last):
  File "/home/lilab/zhangchu1/miniconda3/envs/scarlink-env/bin/scarlink_processing", line 33, in <module>
    sys.exit(load_entry_point('scarlink', 'console_scripts', 'scarlink_processing')())
  File "/home/lilab/software/SCARlink/scarlink/preprocessing/create_h5_files.py", line 44, in main
    rfunc.write_files(archr_out, seurat_out, out_dir, args.window, args.ncores, args.scale)
  File "/home/lilab/zhangchu1/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 208, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/home/lilab/zhangchu1/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/robjects/functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/lilab/zhangchu1/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/lilab/zhangchu1/miniconda3/envs/scarlink-env/lib/python3.8/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: BiocParallel errors
  1 remote errors, element index: 1
  1 unevaluated and other errors
  first remote error:
Error in seq.default(i, length(selected.genes), max_ix): invalid '(to - from)/by'"

These were the info on scATAC-seq ArchR object:
"> scatac.object

           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

class: ArchRProject
outputDirectory: /home/lilab/zhangchu1/6.single_cell/Zhu2023SciAdv/LaFet1/filtered_feature_bc_matrix/ArchR_ATAC_project
samples(1): LaFet1
sampleColData names(1): ArrowFiles
cellColData names(13): Sample TSSEnrichment ... nDiFrags BlacklistRatio
numberOfCells(1): 2773
medianTSS(1): 8.691
medianFrags(1): 21960"

Following were the end section from the ArchRLog file:
"2025-04-29 15:05:39 : Organizing SE TileMatrix from ArrowFile : LaFet1.arrow, 1.22 mins elapsed.

2025-04-29 15:05:39 : se LaFet1, Class = SummarizedExperiment
class: SummarizedExperiment
dim: 6062095 2716
metadata(0):
assays(1): TileMatrix
rownames: NULL
rowData names(3): seqnames idx start
colnames(2716): LaFet1#ATTACTGAGTGAGCAA-1 LaFet1#GCAAGTCGTCCGGTTC-1 ...
  LaFet1#ATACCGGTCTTTGAGA-1 LaFet1#AAGGAAGCATAAAGCA-1
colData names(13): BlacklistRatio nDiFrags ... Sample TSSEnrichment

2025-04-29 15:05:39 : Completed TileMatrix : LaFet1(1 of 1), 1.228 mins elapsed.
2025-04-29 15:05:39 : Organizing colData, 1.228 mins elapsed.
2025-04-29 15:05:39 : Organizing rowData, 1.228 mins elapsed.
2025-04-29 15:05:39 : Organizing rowRanges, 1.229 mins elapsed.
2025-04-29 15:05:41 : Organizing Assays (1 of 1), 1.261 mins elapsed.
2025-04-29 15:05:41 : Constructing SummarizedExperiment, 1.261 mins elapsed.
2025-04-29 15:05:42 : Finished Matrix Creation, 1.287 mins elapsed."
