### ISSUE TITLE
issues replicating spearman correlations

### ISSUE THREAD

**Issue by skwalker** [snehamitra/SCARlink#21]
Hi,

I'm very excited to test out your tool and was able to get it working quite easily, thank you! I am now trying to replicate the correlations that are calculated between the model's predicted gene scores and the true GEX. I have very similar Spearman correlations, but I can't quite replicate the exact numbers stored in the model itself. What I'm trying to do (based on your code in the package) is:
```
## rm is the output of the read_model function for CD8A gene
wmat, intercept = rm.get_gene_coefficient("CD8A")
y_pred = np.ravel(np.exp(np.dot(rm.gene_tile_matrix("CD8A").todense()[rm.test_ix,:], wmat) + intercept))
spearmanr(y_pred, np.array(rm.get_gex_gene("CD8A")[1].todense()).flatten())
```

When I do that, in this example, I get a value of `0.5073211633259`, but the saved correlations are: `{'spearman_correlation_train': 0.4867758191034703, 'spearman_correlation_test': 0.5127208948195778}` (I also get a different value when I try my version on just the training cells, `0.49421998132549116`). I've tested this on all my genes, and all my calculated Spearman correlations are just slightly off from the stored values.

I've also tried using the model itself to get the predictions, but I can't get it to work, which _I think_  is due to the way the weights are stored/saved. Do you know how to fix that? For example, if I do
```
rm.test_model(rm.get_gex_gene("CD8A"), rm.gene_tile_matrix("CD8A").todense(), 
              rm.get_gene_coefficient("CD8A"),
              int(rm.get_gene_alpha("CD8A")))
``` 
I get an error about how I'm setting the weights and the number of layers being wrong. I've also tried only using the first entry in the coefficients tuple for the coefficients, tried it as a matrix, etc but I can't quite get it to work.  I've also tried doing:
```
model_custom = rm.build_model(rm.gene_tile_matrix("CD8A").shape[1], int(rm.get_gene_alpha("CD8A")))
model_custom.set_weights(rm.get_gene_coefficient("CD8A"))
```
but again get issues with the `set_weights` function and the number of layers not being what's expected. Any ideas on how to fix this?

Thanks,
Sarah

**Comment by snehamitra** [comment]
Hi Sarah,

The following code snippet reproduces the saved Spearman correlations for the test set. I included two versions. Version 1 is where you run the function `test_model()` and version 2 is where you predict the values and then calculate the Spearman correlations. 

```python
# extract saved information
f = h5py.File(coef_file, mode = 'r')
train_spearman_corr = f['genes/'+gene].attrs['spearman_correlation_train']
test_spearman_corr = f['genes/'+gene].attrs['spearman_correlation_test']
train_alpha = np.float(f['genes/'+gene].attrs['alpha'])
intercept = f['genes/'+gene].attrs['intercept']
w = f['genes/'+gene][:]
f.close()

test_spearman_corr
'''
Example output
0.34813425362950545
'''

# create model weights list
train_w = [w, np.array([intercept])]
train_w
'''
Example output
[array([[0.00000000e+00],
        [1.57716127e-15],
        [1.18136075e-14],
        ...,
        [5.19944663e-16],
        [2.41295742e-20],
        [7.01942043e-20]], dtype=float32),
 array([-0.87693197], dtype=float32)]
'''

# get inputs
gex_train, gex_test = rm.get_gex_gene(gene)
tile_gene_mat_train, tile_gene_mat_test = rm.gene_tile_matrix_scaled(gene, normalization_factor='ReadsInTSS')

# Version 1: rerun test_model()
test_corr = rm.test_model(np.ravel(gex_test.todense()), tile_gene_mat_test, train_w, np.float(train_alpha))
test_corr
'''
Example output
0.34813425362950545
'''

# Version 2: build model, predict, and calculate Spearman correlation
model_custom = rm.build_model(tile_gene_mat_test.shape[1], np.float(train_alpha))
model_custom.set_weights(train_w)
y_pred = model_custom.predict(tile_gene_mat_test)
stats.spearmanr(np.ravel(gex_test.todense()), y_pred)
'''
Example output
74/74 [==============================] - 0s 969us/step
SignificanceResult(statistic=0.34813425362950545, pvalue=2.3970104754848183e-68)
'''
```
The Spearman correlations reported for the training cells are averaged across 4-fold cross validation [(link)](https://github.com/snehamitra/SCARlink/blob/main/scarlink/src/model.py#L516). So it might be slightly different if it is calculated across all training cells at once.

**Comment by skwalker** [comment]
Oh I see -- I was just using the wrong/unnormalized tile gene matrix! Thank you so much for your (very quick) help.
