### ISSUE TITLE
How can we use Signac processed data instead of ArchR object? 

### ISSUE THREAD

**Issue by momur** [snehamitra/SCARlink#3]
Hello dev team, 

I would like to try out your new tool on my multiomics (scRNA&scATAC-seq) dataset. I processed it with Seurat and Signac. I dont have ArchR object. Is there a way to use Signac processed scATAC-seq data as an input ? 

Thanks

**Comment by snehamitra** [comment]
Hi, SCARlink only supports ArchR objects right now. We will add support for other object formats in the future but we don't have a timeline for it at the moment.

**Comment by feanaros** [comment]
Please I'm interested in the same, thanks
